### ISSUE TITLE
Constructor function for Learning Page

### ISSUE THREAD

**Issue by Tenlia** [AlisonZ/lushootseed#1]

**Comment by derekmhewitt** [comment]
Write Constructor Function

make Flashcards from array of data using FOR loop

randomly select Flashcard by id # for display to the user, display it, and change it's shown property to True, and save array to local storage

button on the page should

When shown = true > 6 show button for the test page

Stretch Goals:
- Make list below "next card" and "show test" buttons that shows previously displayed cards for review
